[package]
name = "big_serde"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true

[dependencies]
num-bigint-dig = { workspace = true, features = ["serde"] }
num-traits = { workspace = true }
serde = { workspace = true }
serde_test = { workspace = true }
